sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t oyashi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true oyashi/react-test npm test

after_success:
  - docker build -t oyashi/multi-client ./client
  - docker build -t oyashi/multi-nginx ./nginx
  - docker build -t oyashi/multi-server ./server
  - docker build -t oyashi/multi-worker ./worker

  # Login to the docker CLI
  # Pass the docker password as standar input to docker login command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Take those images and push them to docker hub
  - docker push "$DOCKER_USERNAME"/multi-client
  - docker push "$DOCKER_USERNAME"/multi-nginx
  - docker push "$DOCKER_USERNAME"/multi-server
  - docker push "$DOCKER_USERNAME"/multi-worker 
